version: "3.9"

networks:
  laravel:
    name: laravel

services:
  nginx:
    build:
        context: .
        dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - laravel

  php:
    build:
      context: .
    container_name: php
    ports:
      ["9000:9000", "9003:9003"]
    expose:
      ["9000", "9003"]
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel